require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const authRoutes = require('./routes/auth');
const awsRoutes = require('./routes/aws');
const app = express();
app.use(helmet({ contentSecurityPolicy: false }));
const allowedOrigins = (process.env.ALLOWED_ORIGINS || '*').split(',').map(s => s.trim());
app.use(cors({ origin: (origin, cb) => { if (!origin || allowedOrigins.includes(origin) || allowedOrigins.includes('*')) return cb(null, true); cb(new Error('CORS')); }, credentials: true }));
app.use(express.json());
app.use('/api/', rateLimit({ windowMs: 60000, max: 100 }));
app.use('/api/auth', authRoutes);
app.use('/api/aws', awsRoutes);
app.get('/api/health', (_, res) => res.json({ status: 'ok' }));
app.use((_, res) => res.status(404).json({ error: 'Not found' }));
app.use((err, _req, res, _next) => { console.error(err.message); res.status(500).json({ error: err.message }); });
module.exports = app;
